CREATE FUNCTION s3test(text) RETURNS text AS
'MODULE_PATHNAME' LANGUAGE C;

CREATE FUNCTION s3_fdw_handler() RETURNS fdw_handler AS
'MODULE_PATHNAME' LANGUAGE C;
CREATE FUNCTION s3_fdw_validator(text[], oid) RETURNS void AS
'MODULE_PATHNAME' LANGUAGE C;

CREATE FOREIGN DATA WRAPPER s3_fdw
	HANDLER s3_fdw_handler
	VALIDATOR s3_fdw_validator;
